#!/bin/bash

if [[ "$1" == "i" || "$1" == "install" ]]; then
    if [[ "$2" == "l" || "$2" == "list" || "$2" == "pkglist" ]]; then
        command=list
    else
        command=package
    fi
elif [[ "$1" == "a" || "$1" == "add" ]]; then
    bash "./helpers/add-ppa" "$2"
else
    command=help
fi

echo ${command}